export const copy = {
  common: {
    nav: {
      logo: {
        alt: 'velovegans logo',
        src: '/assets/logo_size-removebg-preview.png',
      },
      home: 'Home',
      about: 'About',
      recipes: 'Recipes',
      contact: 'Contact',
    },
    footer: {
      companyName: 'VeloVegans.',
      msg: 'All rights reserved.',
      socials: [
        { href: 'https://www.instagram.com', name: 'Instagram' },
        { href: 'https://www.threads.com', name: 'Threads' },
        { href: 'https://www.x.com', name: 'X' },
      ],
    },
  },
  home: {
    description: {
      heading: {
        top: 'VeloVegans',
        bottom: 'Cruelty Free Recipes',
      },
      paragraph: 'Saving the animals and our planet one meal at a time.',
      img: {
        alt: 'velovegans logo',
        src: '/assets/original-logo.jpg',
      },
    },
  },
  contact: {
    description: {
      heading: 'Get in Touch',
      button: 'Work with me',
    },
  },
  about: {
    description: {
      heading: 'About Us',
      paragraph:
        'Welcome to our vegan recipes website, where we celebrate compassion, health, and sustainability. We believe that every meal is an opportunity to make a positive impact on the world. Our recipes are not only delicious but also cruelty-free, meaning they contain no animal products. We are passionate about promoting a lifestyle that respects all living beings. As animal lovers, we understand the importance of kindness and empathy towards our fellow creatures. That is why our recipes are created with love and consideration for animals everywhere. We are also deeply committed to environmental sustainability. Our ingredients are sourced responsibly, and we strive to minimize our carbon footprint in every aspect of our operations. Thank you for joining us on this journey towards a healthier, more compassionate world. Together, we can make a difference, one delicious vegan meal at a time. To kickstart your journey towards saving animals and the planet, here are some useful links:',
    },
  },
  recipesPage: {
    description: {
      heading: {
        top: 'Recipes',
        bottom:
          'Browse our collection of easy, healthy and delicious plant-based recipes.',
      },
      recipes: [
        {
          title: 'Vegan Pasta Primavera',
          image: {
            src: '/assets/vg-pasta-primavera.png',
            alt: 'Pasta Primavera',
          },
          ingredients: [
            '250g pasta',
            '30ml olive oil',
            '2 cloves garlic, minced',
            '1 onion, diced',
            '200g cherry tomatoes, halved',
            '100g broccoli florets',
            '150g sliced bell peppers',
            '150g sliced mushrooms',
            '120ml vegetable broth',
            'Salt and pepper to taste',
            'Fresh basil leaves for garnish',
          ],
          instructions: [
            'Cook pasta according to package instructions. Drain and set aside.',
            'In a large pan, heat olive oil over medium heat. Add garlic and onion, sauté until fragrant.',
            'Add cherry tomatoes, broccoli, bell peppers, and mushrooms. Cook until vegetables are tender.',
            'Pour in vegetable broth and cooked pasta. Toss until well combined.',
            'Season with salt and pepper to taste. Garnish with fresh basil leaves.',
            'Serve hot and enjoy!',
          ],
          cookingTime: '25 minutes',
        },
        {
          title: 'Vegan Chickpea Curry',
          image: {
            src: '/assets/vg-pasta-primavera.png',
            alt: 'Chickpea Curry',
          },
          ingredients: [
            '200g dried chickpeas',
            '30ml olive oil',
            '2 onions, diced',
            '3 cloves garlic, minced',
            '1 red bell pepper, diced',
            '1 yellow bell pepper, diced',
            '400ml coconut milk',
            '400g diced tomatoes',
            '200g spinach leaves',
            '2 tbsp curry powder',
            'Salt and pepper to taste',
            'Fresh coriander for garnish',
          ],
          instructions: [
            'Soak chickpeas overnight. Drain and rinse.',
            'In a large pot, heat olive oil over medium heat. Add onions and garlic, sauté until softened.',
            'Add bell peppers and chickpeas. Cook for 5 minutes.',
            'Stir in coconut milk, diced tomatoes, and curry powder. Simmer for 20 minutes.',
            'Add spinach leaves and cook until wilted. Season with salt and pepper.',
            'Garnish with fresh coriander and serve with rice or naan bread.',
          ],
          cookingTime: '45 minutes',
        },
        {
          title: 'Vegan Lentil Soup',
          image: {
            src: '/assets/lentil-soup.png',
            alt: 'Lentil Soup',
          },
          ingredients: [
            '200g dried lentils',
            '1 onion, diced',
            '2 carrots, diced',
            '2 celery stalks, diced',
            '2 cloves garlic, minced',
            '1 bay leaf',
            '1.5 liters vegetable broth',
            '400g diced tomatoes',
            '30ml olive oil',
            '2 tsp ground cumin',
            '1 tsp paprika',
            'Salt and pepper to taste',
            'Fresh parsley for garnish',
          ],
          instructions: [
            'Rinse lentils under cold water. Set aside.',
            'In a large pot, heat olive oil over medium heat. Add onions, carrots, celery, and garlic. Sauté until softened.',
            'Stir in lentils, diced tomatoes, bay leaf, ground cumin, and paprika.',
            'Pour in vegetable broth. Bring to a boil, then reduce heat and simmer for 30 minutes.',
            'Season with salt and pepper. Garnish with fresh parsley before serving.',
          ],
          cookingTime: '40 minutes',
        },
        {
          title: 'Vegan Spaghetti Bolognese',
          image: {
            src: '/assets/spaghetti_bolognese.jpg',
            alt: 'Spaghetti Bolognese',
          },
          ingredients: [
            '250g spaghetti',
            '30ml olive oil',
            '1 onion, diced',
            '2 carrots, grated',
            '2 celery stalks, diced',
            '200g mushrooms, sliced',
            '400g canned lentils, drained and rinsed',
            '400g canned diced tomatoes',
            '2 cloves garlic, minced',
            '2 tsp dried oregano',
            '1 tsp dried basil',
            'Salt and pepper to taste',
            'Fresh parsley for garnish',
          ],
          instructions: [
            'Cook spaghetti according to package instructions. Drain and set aside.',
            'In a large pan, heat olive oil over medium heat. Add onions, carrots, and celery. Sauté until softened.',
            'Add mushrooms and garlic. Cook until mushrooms are tender.',
            'Stir in canned lentils, diced tomatoes, dried oregano, and dried basil. Simmer for 15 minutes.',
            'Season with salt and pepper. Serve over cooked spaghetti and garnish with fresh parsley.',
          ],
          cookingTime: '35 minutes',
        },
        {
          title: 'Vegan Thai Green Curry',
          image: {
            src: '/assets/thai_green_curry.jpg',
            alt: 'Thai Green Curry',
          },
          ingredients: [
            '200g firm tofu, cubed',
            '30ml vegetable oil',
            '2 tbsp Thai green curry paste',
            '400ml coconut milk',
            '200g mixed vegetables (bell peppers, broccoli, carrots)',
            '100g bamboo shoots',
            '100g baby corn',
            '1 tbsp soy sauce',
            '1 tbsp brown sugar',
            'Salt to taste',
            'Fresh basil leaves for garnish',
          ],
          instructions: [
            'In a large pan, heat vegetable oil over medium heat. Add tofu cubes and fry until golden brown. Set aside.',
            'In the same pan, add Thai green curry paste and fry for 1 minute.',
            'Pour in coconut milk and bring to a simmer. Add mixed vegetables, bamboo shoots, and baby corn. Cook until vegetables are tender.',
            'Stir in fried tofu, soy sauce, brown sugar, and salt. Simmer for another 5 minutes.',
            'Garnish with fresh basil leaves and serve hot with rice.',
          ],
          cookingTime: '30 minutes',
        },
        {
          title: 'Vegan Mushroom Risotto',
          image: {
            src: '/assets/mushroom_risotto.jpg',
            alt: 'Mushroom Risotto',
          },
          ingredients: [
            '200g Arborio rice',
            '1 liter vegetable broth',
            '30ml olive oil',
            '1 onion, diced',
            '2 cloves garlic, minced',
            '200g mushrooms, sliced',
            '60ml dry white wine',
            '50g vegan butter',
            '50g nutritional yeast',
            'Salt and pepper to taste',
            'Fresh parsley for garnish',
          ],
          instructions: [
            'In a saucepan, heat vegetable broth over low heat.',
            'In a separate pan, heat olive oil over medium heat. Add onions and garlic, sauté until softened.',
            'Add Arborio rice and cook for 2 minutes, stirring constantly.',
            'Pour in dry white wine and cook until absorbed.',
            'Gradually add hot vegetable broth, 1 ladleful at a time, stirring frequently. Cook until rice is creamy and tender, about 20 minutes.',
            'Stir in sliced mushrooms, vegan butter, and nutritional yeast. Cook for another 5 minutes.',
            'Season with salt and pepper. Garnish with fresh parsley before serving.',
          ],
          cookingTime: '40 minutes',
        },
        {
          title: "Vegan Lentil Shepherd's Pie",
          image: {
            src: '/assets/shepherds_pie.jpg',
            alt: "Shepherd's Pie",
          },
          ingredients: [
            '200g dried green lentils',
            '500ml vegetable broth',
            '30ml olive oil',
            '1 onion, diced',
            '2 carrots, diced',
            '2 celery stalks, diced',
            '2 cloves garlic, minced',
            '200g frozen peas',
            '2 tbsp tomato paste',
            '1 tsp dried thyme',
            '1 tsp dried rosemary',
            '800g potatoes, peeled and cubed',
            '120ml plant-based milk',
            'Salt and pepper to taste',
          ],
          instructions: [
            'In a saucepan, combine dried green lentils and vegetable broth. Bring to a boil, then reduce heat and simmer for 20 minutes, or until lentils are tender.',
            'In a large pan, heat olive oil over medium heat. Add onions, carrots, celery, and garlic. Sauté until softened.',
            'Stir in cooked lentils, frozen peas, tomato paste, dried thyme, and dried rosemary. Cook for 5 minutes.',
            'Meanwhile, boil potatoes in salted water until tender. Drain and mash with plant-based milk until smooth.',
            'Preheat oven to 200°C (390°F).',
            'Transfer lentil mixture to a baking dish. Spread mashed potatoes evenly over the top.',
            'Bake in the preheated oven for 20-25 minutes, or until the top is golden brown.',
            'Serve hot and enjoy!',
          ],
          cookingTime: '1 hour',
        },
        {
          title: 'Vegan Stuffed Bell Peppers',
          image: {
            src: '/assets/stuffed_peppers.jpg',
            alt: 'Stuffed Bell Peppers',
          },
          ingredients: [
            '4 large bell peppers',
            '200g quinoa',
            '400ml vegetable broth',
            '30ml olive oil',
            '1 onion, diced',
            '2 cloves garlic, minced',
            '200g mushrooms, diced',
            '200g canned black beans, drained and rinsed',
            '200g canned corn, drained',
            '400g canned diced tomatoes',
            '1 tsp ground cumin',
            '1 tsp paprika',
            'Salt and pepper to taste',
            'Fresh parsley for garnish',
          ],
          instructions: [
            'Preheat oven to 180°C (350°F).',
            'Cut the tops off the bell peppers and remove the seeds and membranes.',
            'In a saucepan, combine quinoa and vegetable broth. Bring to a boil, then reduce heat and simmer for 15 minutes, or until quinoa is cooked.',
            'In a large pan, heat olive oil over medium heat. Add onions and garlic, sauté until softened.',
            'Add mushrooms, black beans, corn, canned diced tomatoes, ground cumin, and paprika. Cook for 5 minutes.',
            'Stir in cooked quinoa. Season with salt and pepper.',
            'Stuff bell peppers with quinoa mixture. Place stuffed peppers in a baking dish.',
            'Cover with aluminum foil and bake in the preheated oven for 30 minutes.',
            'Remove foil and bake for an additional 10 minutes, or until peppers are tender.',
            'Garnish with fresh parsley before serving.',
          ],
          cookingTime: '1 hour',
        },
        {
          title: 'Vegan Cauliflower Wings',
          image: {
            src: '/assets/cauliflower_wings.jpg',
            alt: 'Cauliflower Wings',
          },
          ingredients: [
            '1 medium cauliflower head',
            '100g all-purpose flour',
            '120ml plant-based milk',
            '1 tsp garlic powder',
            '1 tsp paprika',
            '1/2 tsp salt',
            '1/4 tsp black pepper',
            '120ml hot sauce',
            '30ml melted vegan butter',
            '1 tbsp maple syrup',
            'Fresh parsley for garnish',
            'Vegan ranch dressing for dipping (optional)',
          ],
          instructions: [
            'Preheat oven to 220°C (425°F). Line a baking sheet with parchment paper.',
            'Cut cauliflower into florets.',
            'In a bowl, whisk together flour, plant-based milk, garlic powder, paprika, salt, and black pepper until smooth.',
            'Dip each cauliflower floret into the batter, coating evenly. Shake off excess batter and place on the prepared baking sheet.',
            'Bake for 20-25 minutes, or until golden brown and crispy.',
            'In a separate bowl, mix together hot sauce, melted vegan butter, and maple syrup.',
            'Remove cauliflower from the oven and toss in the hot sauce mixture until evenly coated.',
            'Return cauliflower to the baking sheet and bake for an additional 10 minutes.',
            'Garnish with fresh parsley and serve hot with vegan ranch dressing for dipping, if desired.',
          ],
          cookingTime: '40 minutes',
        },
        {
          title: 'Vegan Chocolate Avocado Mousse',
          image: {
            src: '/assets/chocolate_mousse.jpg',
            alt: 'Chocolate Avocado Mousse',
          },
          ingredients: [
            '2 ripe avocados',
            '80g cocoa powder',
            '120ml maple syrup',
            '60ml coconut milk',
            '1 tsp vanilla extract',
            'Pinch of salt',
            'Fresh berries for garnish',
            'Shredded coconut for garnish',
          ],
          instructions: [
            'Peel and pit avocados. Place them in a blender or food processor.',
            'Add cocoa powder, maple syrup, coconut milk, vanilla extract, and a pinch of salt to the blender.',
            'Blend until smooth and creamy, scraping down the sides as needed.',
            'Transfer mousse to serving bowls or glasses.',
            'Refrigerate for at least 30 minutes to chill.',
            'Garnish with fresh berries and shredded coconut before serving.',
          ],
          cookingTime: '10 minutes',
        },
        {
          title: 'Vegan Banana Bread',
          image: {
            src: '/assets/banana_bread.jpg',
            alt: 'Banana Bread',
          },
          ingredients: [
            '3 ripe bananas',
            '120ml maple syrup',
            '60ml vegetable oil',
            '60ml plant-based milk',
            '1 tsp vanilla extract',
            '200g all-purpose flour',
            '1 tsp baking soda',
            '1/2 tsp salt',
            '1/2 tsp ground cinnamon',
            '1/4 tsp ground nutmeg',
            '1/4 tsp ground cloves',
            '50g chopped walnuts (optional)',
            '50g vegan chocolate chips (optional)',
          ],
          instructions: [
            'Preheat oven to 180°C (350°F). Grease a 9x5-inch loaf pan or line with parchment paper.',
            'In a large bowl, mash ripe bananas with a fork.',
            'Stir in maple syrup, vegetable oil, plant-based milk, and vanilla extract until well combined.',
            'In a separate bowl, whisk together all-purpose flour, baking soda, salt, ground cinnamon, ground nutmeg, and ground cloves.',
            'Gradually add dry ingredients to wet ingredients, stirring until just combined.',
            'Fold in chopped walnuts and vegan chocolate chips, if using.',
            'Pour batter into prepared loaf pan.',
            'Bake for 50-60 minutes, or until a toothpick inserted into the center comes out clean.',
            'Remove from oven and let cool in the pan for 10 minutes before transferring to a wire rack to cool completely.',
            'Slice and serve!',
          ],
          cookingTime: '1 hour 10 minutes',
        },
        {
          title: 'Vegan Tofu Scramble',
          image: {
            src: '/assets/tofu_scramble.jpg',
            alt: 'Tofu Scramble',
          },
          ingredients: [
            '200g firm tofu',
            '30ml olive oil',
            '1 onion, diced',
            '1 red bell pepper, diced',
            '1 yellow bell pepper, diced',
            '2 cloves garlic, minced',
            '100g cherry tomatoes, halved',
            '2 tbsp nutritional yeast',
            '1 tsp ground turmeric',
            '1/2 tsp ground cumin',
            '1/2 tsp paprika',
            'Salt and pepper to taste',
            'Fresh parsley for garnish',
            'Whole grain bread for serving',
          ],
          instructions: [
            'Wrap tofu in a clean kitchen towel and press to remove excess moisture.',
            'In a large pan, heat olive oil over medium heat. Crumble tofu into the pan and cook until lightly browned.',
            'Add onions, bell peppers, and garlic. Sauté until vegetables are tender.',
            'Stir in cherry tomatoes, nutritional yeast, ground turmeric, ground cumin, and paprika. Cook for 2-3 minutes.',
            'Season with salt and pepper to taste. Garnish with fresh parsley.',
            'Serve hot with whole grain bread.',
          ],
          cookingTime: '20 minutes',
        },
      ],
    },
  },
} as const;
